# Default values for openshift-routes.

replicas: 1
logLevel: 5
nameOverride: ""
fullnameOverride: ""

# This namespace allows you to define where the services are installed into.
# If not set then they use the namespace of the release.
# This is helpful when installing cert manager as a chart dependency (sub chart).
namespace: ""

image:
  # https://github.com/cert-manager/openshift-routes/pkgs/container/cert-manager-openshift-routes
  # the final image is generated as "${registry}/${repostiory}:${tag|digest}"

  # -- Target image repository.
  repository: ghcr.io/cert-manager/cert-manager-openshift-routes
  # -- Target image registry. Will be prepended to the target image repositry if set.
  registry:

  # -- Target image version tag. Defaults to the chart's appVersion.
  tag:

  # -- Target image digest. Will override any tag if set.
  # for example:
  # digest: sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20
  digest:


imagePullSecrets: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

rbac:
  # create (Cluster-) Roles and RoleBindings for the ServiceAccount
  create: true

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

metrics:
  # when enabled, a service is created that exposes the metrics endpoint
  enabled: false
  serviceMonitor:
    # when enabled, a ServiceMonitor object is created - note that his requires the monitoring.coreos.com CRDs!
    enabled: false
    interval: 60s
