{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "openshift-routes.fullname" . }}
  namespace: {{ include "openshift-routes.namespace" . }}
  labels:
    {{- include "openshift-routes.labels" . | nindent 4 }}
spec:
  endpoints:
  - honorLabels: false
    interval: {{ .Values.metrics.serviceMonitor.interval }}
    path: /metrics
    scrapeTimeout: 15s
    targetPort: metrics
  selector:
    matchLabels:
      {{- include "openshift-routes.labels" . | nindent 6 }}
{{- end }}
